import { type SemanticColors, justkitsLight } from "@justkits/colors";

export type { SemanticColors as ColorTokens } from "@justkits/colors";

export const colorCssVariables: SemanticColors = {
  primary: "--color-primary",
  primaryHover: "--color-primary-hover",
  onPrimary: "--color-primary-foreground",
  secondary: "--color-secondary",
  secondaryHover: "--color-secondary-hover",
  onSecondary: "--color-secondary-foreground",
  error: "--color-alert-danger",
  warning: "--color-alert-warning",
  success: "--color-alert-success",
  info: "--color-alert-info",
  background: "--color-background-default",
  backgroundHover: "--color-background-hover",
  backgroundInverted: "--color-background-inverted",
  surface: "--color-background-surface",
  overlay: "--color-background-overlay",
  text: "--color-text-default",
  textMuted: "--color-text-muted",
  textDisabled: "--color-text-disabled",
  border: "--color-border-default",
  borderMuted: "--color-border-muted",
  borderInverted: "--color-border-inverted",
};

export const colorTokens: SemanticColors = {
  primary: `var(${colorCssVariables.primary}, ${justkitsLight.primary})`,
  primaryHover: `var(${colorCssVariables.primaryHover}, ${justkitsLight.primaryHover})`,
  onPrimary: `var(${colorCssVariables.onPrimary}, ${justkitsLight.onPrimary})`,
  secondary: `var(${colorCssVariables.secondary}, ${justkitsLight.secondary})`,
  secondaryHover: `var(${colorCssVariables.secondaryHover}, ${justkitsLight.secondaryHover})`,
  onSecondary: `var(${colorCssVariables.onSecondary}, ${justkitsLight.onSecondary})`,
  error: `var(${colorCssVariables.error}, ${justkitsLight.error})`,
  warning: `var(${colorCssVariables.warning}, ${justkitsLight.warning})`,
  success: `var(${colorCssVariables.success}, ${justkitsLight.success})`,
  info: `var(${colorCssVariables.info}, ${justkitsLight.info})`,
  background: `var(${colorCssVariables.background}, ${justkitsLight.background})`,
  backgroundHover: `var(${colorCssVariables.backgroundHover}, ${justkitsLight.backgroundHover})`,
  backgroundInverted: `var(${colorCssVariables.backgroundInverted}, ${justkitsLight.backgroundInverted})`,
  surface: `var(${colorCssVariables.surface}, ${justkitsLight.surface})`,
  overlay: `var(${colorCssVariables.overlay}, ${justkitsLight.overlay})`,
  text: `var(${colorCssVariables.text}, ${justkitsLight.text})`,
  textMuted: `var(${colorCssVariables.textMuted}, ${justkitsLight.textMuted})`,
  textDisabled: `var(${colorCssVariables.textDisabled}, ${justkitsLight.textDisabled})`,
  border: `var(${colorCssVariables.border}, ${justkitsLight.border})`,
  borderMuted: `var(${colorCssVariables.borderMuted}, ${justkitsLight.borderMuted})`,
  borderInverted: `var(${colorCssVariables.borderInverted}, ${justkitsLight.borderInverted})`,
};
