sonar.projectKey=justkits_design-system
sonar.organization=justkits

sonar.sources=apps

sonar.typescript.tsconfigPaths=**/*/tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/*.*
