sonar.projectKey=justkits_design-system
sonar.organization=justkits

sonar.sources=apps,packages

sonar.typescript.tsconfigPaths=packages/*/tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.js,**/*.config.ts
sonar.coverage.exclusions=**/*.*
sonar.cpd.exclusions=packages/*/tests/unittests/**,packages/*/tests/testcases/**,packages/headless-ui/src/Alert/AlertButton.tsx,packages/headless-ui/src/Alert/AlertTexts.tsx
