sonar.projectKey=justkits_justkits
sonar.organization=justkits

sonar.sources=apps,design

sonar.typescript.tsconfigPaths=**/*/tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/*.*
sonar.cpd.exclusions=**/tests/**
