import type { ColorTokens } from "./types";

export const colorVariables: ColorTokens = {
  primary: "color-primary",
  primaryHover: "color-primary-hover",
  onPrimary: "color-primary-foreground",
  secondary: "color-secondary",
  secondaryHover: "color-secondary-hover",
  onSecondary: "color-secondary-foreground",
  error: "color-alert-danger",
  warning: "color-alert-warning",
  success: "color-alert-success",
  info: "color-alert-info",
  background: "color-background-default",
  backgroundHover: "color-background-hover",
  surface: "color-background-surface",
  overlay: "color-background-overlay",
  text: "color-text-default",
  textMuted: "color-text-muted",
  textDisabled: "color-text-disabled",
  border: "color-border-default",
  borderMuted: "color-border-muted",
  borderInverted: "color-border-inverted",
};

export const colorCSSVariables: ColorTokens = {
  primary: `var(--color-primary)`,
  primaryHover: `var(--color-primary-hover)`,
  onPrimary: `var(--color-primary-foreground)`,
  secondary: `var(--color-secondary)`,
  secondaryHover: `var(--color-secondary-hover)`,
  onSecondary: `var(--color-secondary-foreground)`,
  error: `var(--color-alert-danger)`,
  warning: `var(--color-alert-warning)`,
  success: `var(--color-alert-success)`,
  info: `var(--color-alert-info)`,
  background: `var(--color-background-default)`,
  backgroundHover: `var(--color-background-hover)`,
  surface: `var(--color-background-surface)`,
  overlay: `var(--color-background-overlay)`,
  text: `var(--color-text-default)`,
  textMuted: `var(--color-text-muted)`,
  textDisabled: `var(--color-text-disabled)`,
  border: `var(--color-border-default)`,
  borderMuted: `var(--color-border-muted)`,
  borderInverted: `var(--color-border-inverted)`,
};
